import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Topbar from '@/components/Topbar'
import HeroSection from '@/components/HeroSection'
import PodcastSection from '@/components/PodcastSection'
import RecentSection from '@/components/RecentSection'
import NewsSection from '@/components/NewsSection'
import SponsorSection from '@/components/SponsorSection'
import Footer from '@/components/Footer'
import { NextPage } from 'next'

const inter = Inter({ subsets: ['latin'] })

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Topbar />
        <HeroSection />
        <PodcastSection />
        <RecentSection />
        <NewsSection />
        <SponsorSection />
        <Footer />
      </main>
    </>
  )
}

export default Home;
