import Head from 'next/head'
import { Inter } from 'next/font/google'
import HeroSection from '@/components/HeroSection'
import PodcastSection from '@/components/PodcastSection'
import RecentSection from '@/components/RecentSection'
import NewsSection from '@/components/NewsSection'
import { NextPage } from 'next'

const inter = Inter({ subsets: ['latin'] })

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>&#123;Finsweet App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <HeroSection />
        <PodcastSection />
        <RecentSection />
        <NewsSection />
      </div>
    </>
  )
}

export default Home;
